# Generated by Django 4.1.7 on 2023-02-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_hashtags_product_hashtags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hashtags',
            new_name='Hashtag',
        ),
    ]
